# Generated by Django 3.1.7 on 2021-03-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('car_desc', models.CharField(max_length=1000)),
                ('car_price', models.IntegerField()),
                ('car_image', models.ImageField(default='image/None/noimg.jpg', upload_to='image/')),
            ],
        ),
    ]
